import './globals.css'
import { montserrat, nova_round } from './fonts'
 
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-gray-900 text-slate-100`}>
        <header className='mt-8 w-screen lg:w-1/2 text-center flex flex-col md:flex-row'>
          <h1 className={`${nova_round.className} text-6xl tracking-tight`}>Travis Miller</h1>
          <h2 className={`${nova_round.className} text-xl text-blue-500 leading-6 mb-4 tracking-tighter`}>Full-Stack Web Developer</h2>
          <nav>
            <ul className='w-2/3 mx-auto columns-2'>
              <a href='/'>
                <li className='w-full mb-2 border-slate-100 border-l-4
                 hover:text-xl hover:me-2 hover:bg-gray-800'>
                  About Me
                </li>
              </a>
              <a href='/'>
                <li className='w-full mx-auto mb-2 border-slate-100 border-l-4 
                hover:text-xl'>
                  Projects
                </li>
              </a>
              <a href='/'>
                <li className='w-full mx-auto mb-2 border-slate-100 border-r-4 
                hover:text-xl'>
                  Contact
                </li>
              </a>
              <a href='/'>
                <li className='w-full mx-auto mb-2 border-slate-100 border-r-4 
                hover:text-xl'>
                  Resume
                </li>
              </a>
            </ul>
              
          </nav>
        </header>

        <main className='w-11/12 mx-auto'>
          {children}
        </main>
      </body>
    </html>
  )
}
